sudo: required
language: node_js
node_js:
- node
service:
  - docker

before_install:
  - docker build -t reacttest -f Dockerfile.dev .

script:
 - npm run build
  - docker run reacttest npm run test -- --coverage