sudo: required
install: travis_wait 30 mvn install
language: node_js
node_js:
- node
service:
  - docker

before_install:
  - docker build -t reacttest -f Dockerfile.dev .

script:
  - docker run reacttest npm run test -- --coverage