sudo: required
language: node_js
node_js:
- node
service:
  - docker

before_install:
  - docker build -t reacttest -f Dockerfile.dev .

script:
  - docker run -e CI=true reacttest npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted $AWS_ACCESS_KEY"
  secret_access_key:
    secure: "Encrypted $AWS_SECRET_KEY"
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-536685307823"
  bucket_path: "docker-react"
  on:
    branch: master


